### ISSUE TITLE
The api used in this project can't work now.

### ISSUE THREAD

**Issue by Mr-Lobster** [fredfung007/cityflow-nl#7]
When request the " https://huggingface.co/api/models/checkpoints/bert-base-uncased ",we get nothing but 404, and we found that the  " https://huggingface.co/api " seems provide no service now. It is that the api has been moved out or has been upgrading ?

**Comment by fredfung007** [comment]
Please refer to this: https://huggingface.co/bert-base-uncased

I think it is a configure in transformers.

**Comment by Mr-Lobster** [comment]
I am so appricate it ,but another bug occurs to us.After training the model, different queries have almost same output by using the pretrained bert model.

**Comment by Mr-Lobster** [comment]
Excuse me, there's another problem.Where can i find the file named "data/test-gt.json" which seems neccessary for the evaluation? I am so grateful.

**Comment by fredfung007** [comment]
This is hold out. You won't be able to get that.
