### ISSUE TITLE
test-gt.json file

### ISSUE THREAD

**Issue by daliuying** [fredfung007/cityflow-nl#9]
Hello, may I ask where I can find the test-gt.json file when evaluating the effect of the model?

**Comment by fredfung007** [comment]
`test_gt.json` is held out for evaluation at the AI City Challenge. You may use the test server here: https://www.aicitychallenge.org/2021-evaluation-system/

**Comment by zrxaaa** [comment]
> Hello, may I ask where I can find the test-gt.json file when evaluating the effect of the model?
Hello, have you found this file？？
